#!/usr/bin/env python

import argparse
import os
from index import make_index
from recipe_pages import get_html_files

if not os.path.isdir('html'):
    os.makedirs('html')

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(title='subcommands',
                                   description='valid subcommands',
                                   help='additional help',
                                   dest='command')

subparsers.add_parser('index')
subparsers.add_parser('html')

#TODO: subparsers.add_parser('rss')

subparsers.add_parser('build')

#TODO: subparsers.add_parser('deploy')

args = parser.parse_args()

if args.command == 'index':
    make_index()

elif args.command == 'html':
    get_html_files()

elif args.command == 'build':
    make_index()
    get_html_files()
    
